/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_arraylistjni_HelloJni */

#ifndef _Included_com_example_arraylistjni_HelloJni
#define _Included_com_example_arraylistjni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_arraylistjni_HelloJni
 * Method:    setUser
 * Signature: (Lcom/example/arraylistjni/User;)V
 */
JNIEXPORT void JNICALL Java_com_example_arraylistjni_HelloJni_setUser
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_arraylistjni_HelloJni
 * Method:    getUser
 * Signature: ()Lcom/example/arraylistjni/User;
 */
JNIEXPORT jobject JNICALL Java_com_example_arraylistjni_HelloJni_getUser
  (JNIEnv *, jobject);

/*
 * Class:     com_example_arraylistjni_HelloJni
 * Method:    setUserList
 * Signature: (Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_example_arraylistjni_HelloJni_setUserList
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_arraylistjni_HelloJni
 * Method:    getUserList
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_example_arraylistjni_HelloJni_getUserList
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
